name: Run suma.py

on:
  push:
    branches: [ main, agregar-script-simple ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # permite correrlo manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar suma.py
        run: python suma.py
